#!/usr/bin/env php
<?php

// Be careful of directory settings
$app_dir = __DIR__ . '/app';
$project_dir = dirname(__DIR__);

require_once($project_dir . '/vendor/autoload.php');

$daw = \Remix\Audio::getInstance(true)->daw;
$daw->initialize($app_dir)->playCli($argv);
$daw = null;
