#!/usr/bin/env php
<?php

// Be careful of directory settings
$app_dir = __DIR__ . '/app';
$project_dir = __DIR__;

require_once($project_dir . '/../vendor/autoload.php');

\Remix\Audio::getInstance(true) // the arg in getInstance means debug mode
    ->daw
    ->initialize($app_dir)
    ->playCli($argv);
